name: nnet

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.8
  - pip
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - pytask >=0.2
  - tqdm
  - pandas
  - numpy
  - jupyterlab
  - seaborn
  - scikit-learn
  - catboost
  - tensorflow
  - keras

  # Misc
  - snakeviz
  - black
  - nb_black
  - ipython
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pip:
    - -e .
    - black
    - blackcellmagic
    - pre-commit
